custom_components/evohome_cc/__init__.py
custom_components/evohome_cc/climate.py
custom_components/evohome_cc/schema.py

Because of the change in default behaviour when setting a zone temperature from advanced_override to permanent_override, this pull request creates a new optional configuration parameter:
```
evohome_cc:
...
advanced_override: true
```
If the parameter is set to `true` or does not exist, the behaviour of `set_temperature()` is `ZoneMode.ADVANCED`. If the parameter is set to `false`, behaviour is a permanent override.
I realise that a change to allow profiles is coming soon (in **ramses_rf**), but this is a stop-gap measure until that time to allow those who find the current default behaviour unworkable.

advanced_override config option

---

custom_components/ramses_cc/__init__.py
custom_components/ramses_cc/binary_sensor.py
custom_components/ramses_cc/climate.py
custom_components/ramses_cc/climate_heat.py
custom_components/ramses_cc/const.py
custom_components/ramses_cc/helpers.py
custom_components/ramses_cc/remote.py
custom_components/ramses_cc/schemas.py
custom_components/ramses_cc/sensor.py
custom_components/ramses_cc/test_schema.py
custom_components/ramses_cc/water_heater.py

As requested in forum.
This should fix annotation errors for python <3.10.

Add from __future__ import annotations

---

custom_components/ramses_cc/__init__.py
custom_components/ramses_cc/manifest.json
custom_components/ramses_cc/version.py

This also removes the info log about versions on startup, but it didn't seem like that was a huge loss as:
- It's not something I've seen other components do
- Anyone installing from HACS can check the installed version there
- Anyone installing manually can check the manifest

Correct manifest version and remove version constant

---

custom_components/ramses_cc/water_heater.py

Also renames `MODE_HA_TO_EVO` to `MODE_HA_TO_RAMSES` as I believe I am correct in thinking that the DhwZone is not necessarily an evo zone.

Remove unused water heater constants

---

custom_components/ramses_cc/water_heater.py

This conforms to the core component naming conventions.

Rename water heater entity class

---

custom_components/ramses_cc/__init__.py

This isn't used at present but will come into play later when we forward config entries to each of the platforms.

Add remote to list of platforms

---

custom_components/ramses_cc/climate.py

I believe this is the intended behaviour based on [services.yaml](https://github.com/zxdavb/ramses_cc/blob/7fcf48ae23a7c5073addbfd25fd606c061ef3457/custom_components/ramses_cc/services.yaml#L150).
The naming of the arguments seems a bit odd to me, so perhaps a future candidate for deprecation/renaming?

Fix system mode period/duration args

---

custom_components/ramses_cc/__init__.py
custom_components/ramses_cc/binary_sensor.py
custom_components/ramses_cc/broker.py
custom_components/ramses_cc/climate.py
custom_components/ramses_cc/remote.py
custom_components/ramses_cc/schemas.py
custom_components/ramses_cc/sensor.py
custom_components/ramses_cc/water_heater.py

Tidies up broker start and polling.
Removes redundant DataUpdateCoordinator as the broker already handles updates on an interval. This is more suited to a single API call that returns data and is intended for use with entities that extend `CoordinatorEntity`. Without such entities in place there are no listeners registered with the coordinator and it never does any polling. It seems like a better idea to stick with the existing broker setup as ideally in future it would be possible to transition to listening to event-based updates from ramses_rf which the DataUpdateCoordinator framework is not suited to.

Tidy up broker

---

custom_components/ramses_cc/broker.py

Hass will never be calling these functions directly.

Remove unnecesary callback annotations from broker update internals

---

custom_components/ramses_cc/binary_sensor.py

As we have a separate available check here then we should always be returning whether or not there is an active fault.

Improve active_fault binary sensor state

---

custom_components/ramses_cc/broker.py
custom_components/ramses_cc/const.py

The config flow changes operate on the state to clear the cache elsewhere so it made sense to move those out into const now.

Minor lint/const cleanup in broker

---

custom_components/ramses_cc/climate.py
custom_components/ramses_cc/remote.py
custom_components/ramses_cc/schemas.py
custom_components/ramses_cc/water_heater.py

I'm inferring from recent changes that this is the preferred location/naming convention. I was just noticing that it was a bit odd having them split across multiple locations when merging into `config-flow`.

Move all service schemas to schemas.py

---

custom_components/ramses_cc/sensor.py

As a side note these should really all be in translations.

Fix typo in HVAC humidity sensor names

---

custom_components/ramses_cc/climate.py
custom_components/ramses_cc/remote.py
custom_components/ramses_cc/sensor.py
custom_components/ramses_cc/water_heater.py

Uses ENTITY_ID_FORMAT for all platforms.
Also fixes incorrect prefix for remote and sensor. Interestingly this got corrected by HA but it's better if it's correct to start with!

Consistent approach to entity ID generation across all platforms

---

custom_components/ramses_cc/climate.py

This seems like the best thing to do to maintain the current behaviour.

Fix type hints for controller temp min/max limits

---

hacs.json

This is very minor but it struck me as odd that the HACS display name does not match the HA component/integration name.
As a side-note the description (read from the GitHub repo) could perhaps also be clearer. Maybe something along the lines of `HA integration for RAMSES II RF heating and HVAC systems.`?
Current:
Proposed:

Make HACS display name consistent with HA component

---

custom_components/ramses_cc/binary_sensor.py
custom_components/ramses_cc/sensor.py

Explicitly set `ramses_rf_attr` so we no longer need to default these.
Follow on from https://github.com/zxdavb/ramses_cc/pull/148#issuecomment-1921031732

Neaten entity descriptions

---

custom_components/ramses_cc/translations/en.json

This helps explain the new immediately clear behaviour as well as why you might want to be doing it in the first place.

Add description to cache clear config options step

---

custom_components/ramses_cc/broker.py

@trvrnrth I wonder if this is a bug - can you just confirm for me?
```python
for device in self._devices + self._systems + self._zones:
self._update_device(device)
```
... should be:
```python
for device in self._devices + self._systems + self._zones + self._dhws:
self._update_device(device)
```

DHW should benefit from `update_device()` too

---

.gitignore
custom_components/ramses_cc/schemas.py
custom_components/ramses_cc/services.yaml
custom_components/ramses_cc/translations/en.json
tests/tests_old/test_services.py

This change adds support for impersonation using the send_packet service.
I use it to send fan_demand packets from my faked CO2 sensor, because ramses_rf doesn't support that yet.
I couldn't practically solve this use-case with a remote, because you have to predefine the commands in a remote, which is not very suitable for fan_demand packets, since you specify the demand percentage - you would need to create 100 commands for it.
I submitted this PR before, I hope you would consider merging it. If not, I will have to switch to using my own fork instead.

Add impersonation support to send_packet service

---

custom_components/ramses_cc/services.yaml

Name of `service` was changed to `action` in UI and to `service action` in code, just as comments

Services note

---

custom_components/ramses_cc/config_flow.py

After using the Clear Caches option myself and being confused how to set it in the UI, propose to change default for both switches to False, because the instruction reads: `Choose items below to immediately clear the cache...` and currently - even if I "choose" (meaning change) nothing - both caches are deleted.

Config_flow Clear Cache tweak

---

custom_components/ramses_cc/services.yaml
custom_components/ramses_cc/translations/en.json
custom_components/ramses_cc/translations/nl.json

- Moved default `en` strings from `services.yaml` to `/translations/en.json`
- Added Dutch translations for all services
- Kept some `name:` values as comments for code readability
- Moved worded `unit_of_measurement` to the description string (e.g. `minutes`), because i18n them is not supported. Leaves room on mobile screen too

Services i18n

---

custom_components/ramses_cc/services.yaml

Replace Action `device_id` field drop-down selectors by `target`s, allowing use of HA system picker by room/floor/device.
Note that Descriptions for entity_ids (now targets) were lost and should be deleted in translations.

Tweak `services`

---

custom_components/ramses_cc/climate.py
custom_components/ramses_cc/schemas.py
custom_components/ramses_cc/water_heater.py
tests/tests_old/test_services.py

Fixes #268
Validates `set_zone_mode`, `set_dhw_mode` and `set_system_made` action call data using the original _nested_ schemas, just before invoking ramses_rf.
The accompanying tests use mocking of ramses_rf Command.set_system_mode() etc. Some timed test proved unreliable and are turned off, so must tweak later. Results are nearly correct ± a few secs.
Edit: system_mode not being returned by `assert mock_method.call_args.kwargs == asserts` is to be expected: it is a positional argument. The validation has already been done before.

Entity Services schema tests

---

custom_components/ramses_cc/config_flow.py

Fix for #287 #275.
- Fix get_options() to preserve options set during config flow
- Add debug logging for port name handling
- Add error handling for missing port names
- Prevents KeyError when port_name is not found
- Prevents Gateway constructor TypeError when port_name is None
Fixes issue where selecting a serial port from the dropdown would result in port_name being lost between config flow steps, causing Gateway initialization to fail.

Fix config serial port error

---

custom_components/ramses_cc/remote.py
custom_components/ramses_cc/schemas.py
tests/tests_old/test_services.py

There are Ramses commands that allow a remote to set the ventilation unit to any percentage between 44% and 89.5%, with a defined resolution. For the Orcon ventilation unit, I identified the relevant command to be `31E0`.
While it's straightforward to calculate the required command for a specific percentage using a Python script and transmit it via the remote, the current implementation of ramses_cc does not support this functionality directly.
Although I believe the ideal solution would be to send arbitrary command strings to the remote in real time, I haven't implemented this yet—mainly because I haven't found a way to do this yet. Instead, I devised a workaround by introducing a new action in ramses_cc called `add_command`. Here's how it can be used:
```yaml
service: ramses.add_command …
```

Add Feature: a ramses_cc.add_command action to add commands outside the config flow

---

custom_components/ramses_cc/broker.py
custom_components/ramses_cc/schemas.py
custom_components/ramses_cc/translations/en.json
custom_components/ramses_cc/translations/nl.json

Fix issue #296 #202 error when turning on force_known_list config option.
Only happens when e.g. there is an orphan that is not also in the known_list, or a cached packet log from an unknown device.
PR skips those and adds dump of config in debug mode.
User should still delete & rebuild caches before restart:

Filter cached packets against known_list

---

custom_components/ramses_cc/manifest.json
requirements_dev.txt
requirements_test.txt

For 0.51.8, pre-commit >= 4.2.0, pytest_homeassistant_custom_component >= 0.13.286

Bump dependencies
